// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Logo_Icon;
extern lv_obj_t * ui_TOTP;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_Logo_Label;
extern lv_obj_t * ui_Battery_Voltage;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Battery_Label;
extern lv_obj_t * ui_WifiOn;
extern lv_obj_t * ui_WifiOff;
extern lv_obj_t * ui_CountDown;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Battery_Voltage;
extern lv_obj_t * uic_WifiOn;
extern lv_obj_t * uic_WifiOff;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

