// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_WifiOff;
lv_obj_t * uic_WifiOn;
lv_obj_t * uic_Battery_Voltage;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Logo_Icon = NULL;
lv_obj_t * ui_TOTP = NULL;
lv_obj_t * ui_Spinner = NULL;
lv_obj_t * ui_Logo_Label = NULL;
lv_obj_t * ui_Battery_Voltage = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Battery_Label = NULL;
lv_obj_t * ui_WifiOn = NULL;
lv_obj_t * ui_WifiOff = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Logo_Icon = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Logo_Icon, &ui_img_gitlab_icon_60x58_png);
    lv_obj_set_width(ui_Logo_Icon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Logo_Icon, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_Logo_Icon, -119);
    lv_obj_set_y(ui_Logo_Icon, -46);
    lv_obj_set_align(ui_Logo_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Logo_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TOTP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TOTP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TOTP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TOTP, 0);
    lv_obj_set_y(ui_TOTP, 17);
    lv_obj_set_align(ui_TOTP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TOTP, "999999");
    lv_obj_set_style_text_font(ui_TOTP, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_Spinner, 1000, 90);
    lv_obj_set_width(ui_Spinner, 50);
    lv_obj_set_height(ui_Spinner, 50);
    lv_obj_set_x(ui_Spinner, 121);
    lv_obj_set_y(ui_Spinner, -47);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Logo_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Logo_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Logo_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Logo_Label, 0);
    lv_obj_set_y(ui_Logo_Label, -45);
    lv_obj_set_align(ui_Logo_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Logo_Label, "GITLABS");
    lv_obj_set_style_text_font(ui_Logo_Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Voltage = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Battery_Voltage, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery_Voltage, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery_Voltage, 54);
    lv_obj_set_height(ui_Battery_Voltage, 10);
    lv_obj_set_x(ui_Battery_Voltage, -118);
    lv_obj_set_y(ui_Battery_Voltage, 72);
    lv_obj_set_align(ui_Battery_Voltage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Battery_Voltage,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_recolor(ui_Battery_Voltage, lv_color_hex(0x1EB02A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Battery_Voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Battery_Voltage, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Battery_Voltage,
                                                                                                      lv_obj_get_style_pad_right(ui_Battery_Voltage, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 133);
    lv_obj_set_y(ui_Temperature, 70);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "99.99c");
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Battery_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Label, -68);
    lv_obj_set_y(ui_Battery_Label, 71);
    lv_obj_set_align(ui_Battery_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Battery_Label, "vBAT");

    ui_WifiOn = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_WifiOn, &ui_img_wifi_png);
    lv_obj_set_width(ui_WifiOn, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_WifiOn, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_WifiOn, 0);
    lv_obj_set_y(ui_WifiOn, 72);
    lv_obj_set_align(ui_WifiOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiOn, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_WifiOn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_WifiOff = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_WifiOff, &ui_img_wifioff_png);
    lv_obj_set_width(ui_WifiOff, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_WifiOff, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_WifiOff, 0);
    lv_obj_set_y(ui_WifiOff, 72);
    lv_obj_set_align(ui_WifiOff, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiOff, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    uic_Battery_Voltage = ui_Battery_Voltage;
    uic_WifiOn = ui_WifiOn;
    uic_WifiOff = ui_WifiOff;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Logo_Icon = NULL;
    ui_TOTP = NULL;
    ui_Spinner = NULL;
    ui_Logo_Label = NULL;
    uic_Battery_Voltage = NULL;
    ui_Battery_Voltage = NULL;
    ui_Temperature = NULL;
    ui_Battery_Label = NULL;
    uic_WifiOn = NULL;
    ui_WifiOn = NULL;
    uic_WifiOff = NULL;
    ui_WifiOff = NULL;

}
